### PR TITLE
Fix modal info display

### PR DESCRIPTION
**Pull request by afsaints0987**
fix-modal-info-display

### CODE REVIEW

**Comment by AdyCastEX** [comment]
@afsaints0987 please open your PRs in your fork instead of here on the main repo to avoid cluttering the pull requests page

**Comment by afsaints0987** [comment]
Hi @AdyCastEX apologize for that, I already managed to open PR from my forked repository. Thanks

**Comment by AdyCastEX** [comment]
> Hi @AdyCastEX apologize for that, I already managed to open PR from my forked repository. Thanks

ok please close these ones once all settled

**Comment by afsaints0987** [comment]
@AdyCastEX already closed all the pull requests. Thanks

**Pull request closed without merging**
