### PR TITLE
Fix/modal info display

### PR DESCRIPTION
**Pull request by josephmario**
gallery.tsx,

Remove s in className="field"

### CODE REVIEW

**Comment by josephmario** [comment]
Hi @AdyCastEX 

Here's the Test Proof:

Thank you
fixmodal-info-display

**Comment by AdyCastEX** [comment]
> Hi @AdyCastEX
> 
> Here's the Test Proof:
> 
> Thank you fixmodal-info-display

please open a PR on your fork instead of the main repo to avoid filling up the pull requests page. Close this PR once transferred. Apply also to other PRs you opened

**Comment by AdyCastEX** [comment]
> > Hi @AdyCastEX
> > Here's the Test Proof:
> > Thank you fixmodal-info-display
> 
> please open a PR on your fork instead of the main repo to avoid filling up the pull requests page. Close this PR once transferred. Apply also to other PRs you opened

@josephmario following up on this please transfer your PR

**Comment by josephmario** [comment]
Hi @AdyCastEX, 

Good Day,

Sorry I don't understand, i create PR using my fork

**Comment by AdyCastEX** [comment]
> Hi @AdyCastEX,
> 
> Good Day,
> 
> Sorry I don't understand, i create PR using my fork

ah ideally you should have created a new branch from your version of the branch e.g `josephmario:fix/modal-info-display` and when you created a PR it should be directed to a branch in your fork instead of the original one (AdyCastEX:fix/modal-info-display) so it appears in the pull requests of your fork instead of this one.

**Comment by josephmario** [comment]
I see @AdyCastEX working on it

**Comment by josephmario** [comment]
Hi @AdyCastEX,

let me know if this is correct,

https://github.com/josephmario/frontend_test/pull/1

I'll do the rest PR,

Thank you

**Comment by AdyCastEX** [comment]
> Hi @AdyCastEX,
> 
> let me know if this is correct,
> 
> [josephmario#1](https://github.com/josephmario/frontend_test/pull/1)
> 
> I'll do the rest PR,
> 
> Thank you

that's good

**Pull request closed without merging**
